//! Urotif's *backend*, not its parser or native interpreter.
//! Fortran supplies validated, resolved IR through ABI 1. This library lowers
//! that IR into WebAssembly's structured control flow and encodes the module.
mod capsule;
mod fortran_target;
pub mod foundation;
pub mod host;
mod limits;
pub mod typed;
mod typed_emit;

use std::fmt::Write as FmtWrite;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::{fs, slice, str};

pub const ABI_VERSION: i32 = 1;
const STACK_CAP: i32 = 2048;
const CALL_CAP: i32 = 1024;
const VAR_CAP: i32 = 256;

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct Instruction {
    pub op: i32,
    pub arg: i32,
    pub line: i32,
    pub column: i32,
    pub number: f64,
}

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct TextSpan {
    pub offset: i32,
    pub length: i32,
}

fn validate(code: &[Instruction], entry: i32, texts: &[Vec<u8>]) -> Result<(), String> {
    if code.is_empty() || code.len() > 8192 {
        return Err("instruction count must be 1..8192".into());
    }
    if entry < 0 || entry as usize >= code.len() {
        return Err("entry point is outside the program".into());
    }
    if texts.len() > 1024 || texts.iter().any(|s| s.len() > 2048) {
        return Err("text pool exceeds the core limits".into());
    }
    for (pc, i) in code.iter().enumerate() {
        if !(0..=29).contains(&i.op) || i.line < 1 || i.column < 1 || !i.number.is_finite() {
            return Err(format!("invalid instruction at PC {pc}"));
        }
        if (14..=17).contains(&i.op) && (i.arg < 0 || i.arg as usize >= code.len()) {
            return Err(format!("invalid jump/call target at PC {pc}"));
        }
        if i.op == 2 && (i.arg < 0 || i.arg as usize >= texts.len()) {
            return Err(format!("invalid text index at PC {pc}"));
        }
        if (i.op == 25 || i.op == 26) && !(0..VAR_CAP).contains(&i.arg) {
            return Err(format!("invalid register at PC {pc}"));
        }
    }
    Ok(())
}

fn bytes_wat(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 3);
    for b in bytes {
        write!(s, "\\{b:02x}").unwrap();
    }
    s
}

fn error_if(out: &mut String, condition: &str, code: i32) {
    writeln!(out, "(if {condition} (then (return (i32.const {code}))))").unwrap();
}

fn num_checks(out: &mut String, binary: bool) {
    error_if(out, "(i32.ne (i32.load (local.get $a)) (i32.const 0))", 3);
    if binary {
        error_if(out, "(i32.ne (i32.load (local.get $b)) (i32.const 0))", 3);
        out.push_str("(local.set $x (f64.load offset=8 (local.get $b)))\n");
    }
    out.push_str("(local.set $y (f64.load offset=8 (local.get $a)))\n");
}

/// A program-specific dispatch loop implements arbitrary Urotif gotos without
/// pretending that Rust or WASM offers an unstructured source-level goto.
/// This deliberately simple first backend emits O(N) dispatch, not an optimizer.
pub fn emit_wat(code: &[Instruction], entry: i32, texts: &[Vec<u8>]) -> Result<String, String> {
    validate(code, entry, texts)?;
    // Static memory layout: newline, text descriptor table, text bytes,
    // 16-byte tagged data stack slots, global registers, 4-byte return PCs.
    let mut data = vec![0u8; 16 + texts.len() * 8];
    data[0] = b'\n';
    for (id, text) in texts.iter().enumerate() {
        let ptr = data.len() as u32;
        let len = text.len() as u32;
        data[16 + id * 8..20 + id * 8].copy_from_slice(&ptr.to_le_bytes());
        data[20 + id * 8..24 + id * 8].copy_from_slice(&len.to_le_bytes());
        data.extend(text);
    }
    let stack_base = ((data.len() + 15) & !15) as i32;
    let var_base = stack_base + STACK_CAP * 16;
    let return_base = var_base + VAR_CAP * 16;
    let pages = (return_base + CALL_CAP * 4 + 65535) / 65536;
    let mut out = format!(
        r#";; Generated by the Rust chain from Fortran IR. Urotif ABI 1.
(module
 (import "urotif" "write_text" (func $write_text (param i32 i32)))
 (import "urotif" "write_number" (func $write_number (param f64)))
 (import "urotif" "read_number" (func $read_number (result f64)))
 (memory (export "memory") {pages} {pages})
 (data (i32.const 0) "{data}")
 (global $sp (mut i32) (i32.const 0))
 (global $rp (mut i32) (i32.const 0))
 (global $line (mut i32) (i32.const 1))
 (global $column (mut i32) (i32.const 1))
 (global $steps (mut i32) (i32.const 0))
 (func (export "urotif_error_line") (result i32) (global.get $line))
 (func (export "urotif_error_column") (result i32) (global.get $column))
 (func (export "urotif_steps") (result i32) (global.get $steps))
 (func $slot (param $i i32) (result i32)
   (i32.add (i32.const {stack_base}) (i32.mul (local.get $i) (i32.const 16))))
 (func $copy (param $dst i32) (param $src i32)
   (i64.store (local.get $dst) (i64.load (local.get $src)))
   (i64.store offset=8 (local.get $dst) (i64.load offset=8 (local.get $src))))
 (func $setnum (param $dst i32) (param $x f64)
   (i32.store (local.get $dst) (i32.const 0))
   (i32.store offset=4 (local.get $dst) (i32.const 0))
   (f64.store offset=8 (local.get $dst) (local.get $x)))
 (func $finite (param $x f64) (result i32)
   (f64.le (f64.abs (local.get $x)) (f64.const 1.7976931348623157e308)))
 (func $print (param $src i32) (local $table i32)
   (if (i32.eqz (i32.load (local.get $src)))
     (then (call $write_number (f64.load offset=8 (local.get $src))))
     (else
       (local.set $table (i32.add (i32.const 16)
         (i32.mul (i32.load offset=4 (local.get $src)) (i32.const 8))))
       (call $write_text (i32.load (local.get $table))
         (i32.load offset=4 (local.get $table))))))
 (func (export "urotif_run") (param $fuel i32) (result i32)
   (local $pc i32) (local $a i32) (local $b i32) (local $c i32)
   (local $k i32) (local $same i32) (local $tmp1 i64) (local $tmp2 i64)
   (local $x f64) (local $y f64) (local $z f64)
   (global.set $sp (i32.const 0))
   (global.set $rp (i32.const 0))
   (global.set $steps (i32.const 0))
   (local.set $pc (i32.const {entry}))
   (local.set $k (i32.const 0))
   (loop $clear_registers
     (i32.store (i32.add (i32.const {var_base})
       (i32.mul (local.get $k) (i32.const 16))) (i32.const -1))
     (local.set $k (i32.add (local.get $k) (i32.const 1)))
     (br_if $clear_registers (i32.lt_u (local.get $k) (i32.const {VAR_CAP}))))
   (loop $dispatch
"#,
        data = bytes_wat(&data),
    );
    for (pc, i) in code.iter().enumerate() {
        writeln!(
            out,
            ";; PC {pc}; Urotif {}:{}; opcode {}",
            i.line, i.column, i.op
        )
        .unwrap();
        writeln!(out, "(if (i32.eq (local.get $pc) (i32.const {pc})) (then").unwrap();
        writeln!(out, "(global.set $line (i32.const {}))", i.line).unwrap();
        writeln!(out, "(global.set $column (i32.const {}))", i.column).unwrap();
        error_if(&mut out, "(i32.or (i32.le_s (local.get $fuel) (i32.const 0)) (i32.ge_u (global.get $steps) (local.get $fuel)))", 8);
        out.push_str("(global.set $steps (i32.add (global.get $steps) (i32.const 1)))\n");
        let need = match i.op {
            3 | 4 | 11 | 12 | 13 | 15 | 16 | 25 => 1,
            5 | 6 | 7 | 8 | 9 | 10 | 19 | 20 | 21 | 22 | 23 | 24 | 28 => 2,
            29 => 3,
            _ => 0,
        };
        if need > 0 {
            error_if(
                &mut out,
                &format!("(i32.lt_u (global.get $sp) (i32.const {need}))"),
                1,
            );
            out.push_str("(local.set $a (call $slot (i32.sub (global.get $sp) (i32.const 1))))\n");
        }
        if need > 1 {
            out.push_str("(local.set $b (call $slot (i32.sub (global.get $sp) (i32.const 2))))\n");
        }
        if matches!(i.op, 1 | 2 | 3 | 6 | 26 | 27) {
            error_if(
                &mut out,
                &format!("(i32.ge_u (global.get $sp) (i32.const {STACK_CAP}))"),
                2,
            );
        }
        let mut next = true;
        match i.op {
            0 => out.push_str("(return (i32.const 0))\n"),
            1 => writeln!(
                out,
                "(call $setnum (call $slot (global.get $sp)) (f64.const {:.17e}))",
                i.number
            )
            .unwrap(),
            2 => {
                out.push_str("(local.set $a (call $slot (global.get $sp)))\n");
                out.push_str("(i32.store (local.get $a) (i32.const 1))\n");
                writeln!(
                    out,
                    "(i32.store offset=4 (local.get $a) (i32.const {}))",
                    i.arg
                )
                .unwrap();
                out.push_str("(i64.store offset=8 (local.get $a) (i64.const 0))\n");
            }
            3 => out.push_str("(call $copy (call $slot (global.get $sp)) (local.get $a))\n"),
            4 => {}
            5 => {
                out.push_str("(local.set $tmp1 (i64.load (local.get $a)))\n(local.set $tmp2 (i64.load offset=8 (local.get $a)))\n");
                out.push_str("(call $copy (local.get $a) (local.get $b))\n(i64.store (local.get $b) (local.get $tmp1))\n(i64.store offset=8 (local.get $b) (local.get $tmp2))\n");
            }
            6 => out.push_str("(call $copy (call $slot (global.get $sp)) (local.get $b))\n"),
            7 | 8 | 9 | 10 | 21 | 22 | 23 | 24 | 28 => {
                num_checks(&mut out, true);
                if i.op == 10 || i.op == 28 {
                    error_if(&mut out, "(f64.eq (local.get $y) (f64.const 0))", 4);
                }
                let expr = match i.op {
                    7 => "(f64.add (local.get $x) (local.get $y))",
                    8 => "(f64.sub (local.get $x) (local.get $y))",
                    9 => "(f64.mul (local.get $x) (local.get $y))",
                    10 => "(f64.div (local.get $x) (local.get $y))",
                    21 => "(f64.convert_i32_u (f64.lt (local.get $x) (local.get $y)))",
                    22 => "(f64.convert_i32_u (f64.le (local.get $x) (local.get $y)))",
                    23 => "(f64.convert_i32_u (f64.gt (local.get $x) (local.get $y)))",
                    24 => "(f64.convert_i32_u (f64.ge (local.get $x) (local.get $y)))",
                    28 => {
                        out.push_str("(local.set $z (f64.div (local.get $x) (local.get $y)))\n");
                        error_if(&mut out, "(i32.eqz (call $finite (local.get $z)))", 10);
                        "(f64.sub (local.get $x) (f64.mul (f64.trunc (local.get $z)) (local.get $y)))"
                    }
                    _ => unreachable!(),
                };
                writeln!(out, "(local.set $z {expr})").unwrap();
                error_if(&mut out, "(i32.eqz (call $finite (local.get $z)))", 10);
                out.push_str("(call $setnum (local.get $b) (local.get $z))\n");
            }
            11 => {
                num_checks(&mut out, false);
                out.push_str("(call $setnum (local.get $a) (f64.neg (local.get $y)))\n");
            }
            12 | 13 => {
                out.push_str("(call $print (local.get $a))\n");
                if i.op == 13 {
                    out.push_str("(call $write_text (i32.const 0) (i32.const 1))\n");
                }
            }
            14 => {
                writeln!(out, "(local.set $pc (i32.const {}))", i.arg).unwrap();
                next = false;
            }
            15 | 16 => {
                num_checks(&mut out, false);
                let test = if i.op == 15 { "eq" } else { "ne" };
                writeln!(out, "(if (f64.{test} (local.get $y) (f64.const 0)) (then (local.set $pc (i32.const {}))) (else (local.set $pc (i32.const {}))))", i.arg, pc + 1).unwrap();
                next = false;
            }
            17 => {
                error_if(
                    &mut out,
                    &format!("(i32.ge_u (global.get $rp) (i32.const {CALL_CAP}))"),
                    5,
                );
                writeln!(out, "(i32.store (i32.add (i32.const {return_base}) (i32.mul (global.get $rp) (i32.const 4))) (i32.const {}))", pc + 1).unwrap();
                out.push_str("(global.set $rp (i32.add (global.get $rp) (i32.const 1)))\n");
                writeln!(out, "(local.set $pc (i32.const {}))", i.arg).unwrap();
                next = false;
            }
            18 => {
                out.push_str("(if (i32.eqz (global.get $rp)) (then (return (i32.const 0))))\n");
                out.push_str("(global.set $rp (i32.sub (global.get $rp) (i32.const 1)))\n");
                writeln!(out, "(local.set $pc (i32.load (i32.add (i32.const {return_base}) (i32.mul (global.get $rp) (i32.const 4)))))").unwrap();
                next = false;
            }
            19 | 20 => {
                out.push_str(r#"
(local.set $same (i32.const 0))
(if (i32.eq (i32.load (local.get $a)) (i32.load (local.get $b)))
 (then (if (i32.eqz (i32.load (local.get $a)))
  (then (local.set $same (f64.eq (f64.load offset=8 (local.get $a)) (f64.load offset=8 (local.get $b)))))
  (else (local.set $same (i32.eq (i32.load offset=4 (local.get $a)) (i32.load offset=4 (local.get $b))))))))
"#);
                if i.op == 20 {
                    out.push_str("(local.set $same (i32.eqz (local.get $same)))\n");
                }
                out.push_str(
                    "(call $setnum (local.get $b) (f64.convert_i32_u (local.get $same)))\n",
                );
            }
            25 => writeln!(
                out,
                "(call $copy (i32.const {}) (local.get $a))",
                var_base + i.arg * 16
            )
            .unwrap(),
            26 => {
                let addr = var_base + i.arg * 16;
                error_if(
                    &mut out,
                    &format!("(i32.eq (i32.load (i32.const {addr})) (i32.const -1))"),
                    6,
                );
                writeln!(
                    out,
                    "(call $copy (call $slot (global.get $sp)) (i32.const {addr}))"
                )
                .unwrap();
            }
            27 => {
                out.push_str("(local.set $z (call $read_number))\n");
                error_if(&mut out, "(i32.eqz (call $finite (local.get $z)))", 9);
                out.push_str("(call $setnum (call $slot (global.get $sp)) (local.get $z))\n");
            }
            29 => {
                out.push_str(
                    "(local.set $c (call $slot (i32.sub (global.get $sp) (i32.const 3))))\n",
                );
                out.push_str("(local.set $tmp1 (i64.load (local.get $c)))\n(local.set $tmp2 (i64.load offset=8 (local.get $c)))\n");
                out.push_str("(call $copy (local.get $c) (local.get $b))\n(call $copy (local.get $b) (local.get $a))\n");
                out.push_str("(i64.store (local.get $a) (local.get $tmp1))\n(i64.store offset=8 (local.get $a) (local.get $tmp2))\n");
            }
            _ => unreachable!(),
        }
        let delta = match i.op {
            1 | 2 | 3 | 6 | 26 | 27 => 1,
            4 | 7 | 8 | 9 | 10 | 12 | 13 | 15 | 16 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 28 => -1,
            _ => 0,
        };
        if delta != 0 {
            writeln!(
                out,
                "(global.set $sp (i32.add (global.get $sp) (i32.const {delta})))"
            )
            .unwrap();
        }
        if next {
            writeln!(out, "(local.set $pc (i32.const {}))", pc + 1).unwrap();
        }
        out.push_str("(br $dispatch)\n))\n");
    }
    out.push_str("(return (i32.const 7))\n)\n(i32.const 0)\n)\n)\n");
    Ok(out)
}

unsafe fn checked_slice<'a, T>(ptr: *const T, len: usize, max: usize) -> Result<&'a [T], String> {
    if len > max {
        return Err("FFI array exceeds its documented limit".into());
    }
    if len == 0 {
        return Ok(&[]);
    }
    if ptr.is_null() {
        return Err("null FFI input buffer".into());
    }
    // The caller guarantees validity/alignment/lifetime as required by the ABI.
    Ok(unsafe { slice::from_raw_parts(ptr, len) })
}

/// Emit a .wasm (format 0) or .wat (format 1) from Fortran's resolved IR.
/// Return 0 on success, 1 on a reported error, 2 if a Rust panic was caught.
///
/// # Safety
/// Nonempty input pointers must reference readable aligned arrays of their
/// declared lengths for the duration of this call. `error` must reference a
/// writable byte buffer of `error_cap` bytes, must not alias input, and may be
/// null only for a zero-length buffer. No pointer is retained after return.
#[no_mangle]
pub unsafe extern "C" fn urotif_backend_emit(
    abi: i32,
    code: *const Instruction,
    count: usize,
    entry: i32,
    text_bytes: *const u8,
    byte_count: usize,
    spans: *const TextSpan,
    text_count: usize,
    path: *const u8,
    path_len: usize,
    format: i32,
    error: *mut u8,
    error_cap: usize,
) -> i32 {
    let result = catch_unwind(AssertUnwindSafe(|| -> Result<(), String> {
        if abi != ABI_VERSION {
            return Err("unsupported Urotif IR ABI version".into());
        }
        if format != 0 && format != 1 {
            return Err("format must be 0 (WASM) or 1 (WAT)".into());
        }
        let code = unsafe { checked_slice(code, count, 8192)? };
        let blob = unsafe { checked_slice(text_bytes, byte_count, 1024 * 2048)? };
        let spans = unsafe { checked_slice(spans, text_count, 1024)? };
        let path = unsafe { checked_slice(path, path_len, 4096)? };
        let path = str::from_utf8(path).map_err(|_| "output path must be UTF-8")?;
        if path.is_empty() {
            return Err("output path is empty".into());
        }
        let mut texts = Vec::with_capacity(spans.len());
        for span in spans {
            if span.offset < 0 || span.length < 0 || span.length > 2048 {
                return Err("invalid text span".into());
            }
            let start = span.offset as usize;
            let end = start
                .checked_add(span.length as usize)
                .ok_or("text span overflow")?;
            texts.push(
                blob.get(start..end)
                    .ok_or("text span outside byte buffer")?
                    .to_vec(),
            );
        }
        let wat = emit_wat(code, entry, &texts)?;
        let output = if format == 0 {
            wat::parse_str(&wat).map_err(|e| format!("WASM encoding failed: {e}"))?
        } else {
            wat.into_bytes()
        };
        fs::write(path, output).map_err(|e| format!("cannot write output: {e}"))?;
        Ok(())
    }));
    let (status, message) = match result {
        Ok(Ok(())) => (0, String::new()),
        Ok(Err(e)) => (1, e),
        Err(_) => (
            2,
            "Rust backend panic contained at the C ABI boundary".into(),
        ),
    };
    if !error.is_null() && error_cap > 0 {
        let n = message.len().min(error_cap - 1);
        unsafe {
            std::ptr::copy_nonoverlapping(message.as_ptr(), error, n);
            *error.add(n) = 0;
        }
    }
    status
}

#[cfg(test)]
mod tests {
    use super::*;
    fn ins(op: i32, arg: i32) -> Instruction {
        Instruction {
            op,
            arg,
            line: 1,
            column: 1,
            number: 0.0,
        }
    }
    #[test]
    fn c_layout() {
        assert_eq!(std::mem::size_of::<Instruction>(), 24);
        assert_eq!(std::mem::align_of::<Instruction>(), 8);
        assert_eq!(std::mem::size_of::<TextSpan>(), 8);
    }
    #[test]
    fn minimal_module() {
        let wat = emit_wat(&[ins(0, 0)], 0, &[]).unwrap();
        let wasm = wat::parse_str(wat).unwrap();
        assert_eq!(&wasm[..4], b"\0asm");
    }
    #[test]
    fn validate_targets() {
        assert!(emit_wat(&[ins(14, 99)], 0, &[]).is_err());
        assert!(emit_wat(&[ins(2, 0)], 0, &[]).is_err());
        assert!(emit_wat(&[ins(25, 256)], 0, &[]).is_err());
    }
    #[test]
    fn every_opcode_encodes() {
        let mut code: Vec<_> = (0..=29).map(|op| ins(op, 0)).collect();
        code.push(ins(0, 0));
        wat::parse_str(emit_wat(&code, 0, &[b"x".to_vec()]).unwrap()).unwrap();
    }
    #[test]
    fn abi_rejection_is_reported() {
        let mut error = [0u8; 256];
        let result = unsafe {
            urotif_backend_emit(
                99,
                std::ptr::null(),
                0,
                0,
                std::ptr::null(),
                0,
                std::ptr::null(),
                0,
                std::ptr::null(),
                0,
                0,
                error.as_mut_ptr(),
                error.len(),
            )
        };
        assert_eq!(result, 1);
        assert!(str::from_utf8(&error).unwrap().contains("ABI version"));
    }
    #[test]
    fn null_input_is_reported() {
        let mut error = [0u8; 256];
        let result = unsafe {
            urotif_backend_emit(
                1,
                std::ptr::null(),
                1,
                0,
                std::ptr::null(),
                0,
                std::ptr::null(),
                0,
                std::ptr::null(),
                0,
                0,
                error.as_mut_ptr(),
                error.len(),
            )
        };
        assert_eq!(result, 1);
        assert!(str::from_utf8(&error).unwrap().contains("null"));
    }
}
